CREATE TABLE AREAS (ID SERIAL NOT NULL, AREA JSONB, CONSTRAINT areas_pkey PRIMARY KEY (ID));
CREATE TABLE ARTISTS (ID SERIAL NOT NULL, ARTIST JSONB, CONSTRAINT artists_pkey PRIMARY KEY (ID));
CREATE TABLE FORMATS (ID SERIAL NOT NULL, FORMAT JSONB, CONSTRAINT formats_pkey PRIMARY KEY (ID));
CREATE TABLE LABELS (ID SERIAL NOT NULL, LABEL JSONB, CONSTRAINT labels_pkey PRIMARY KEY (ID));
CREATE TABLE LANGUAGES (ID SERIAL NOT NULL, LANGUAGE JSONB, CONSTRAINT languages_pkey PRIMARY KEY (ID));
CREATE TABLE MEDIUMS (ID SERIAL NOT NULL, MEDIUM JSONB, CONSTRAINT mediums_pkey PRIMARY KEY (ID));
CREATE TABLE PLACES (ID SERIAL NOT NULL, PLACE JSONB, CONSTRAINT places_pkey PRIMARY KEY (ID));
CREATE TABLE RECORDS (ID SERIAL NOT NULL, RECORD JSONB, CONSTRAINT records_pkey PRIMARY KEY (ID));
CREATE TABLE RELEASES (ID SERIAL NOT NULL, RELEASE JSONB, CONSTRAINT releases_pkey PRIMARY KEY (ID));
CREATE TABLE TRACKS (ID SERIAL NOT NULL, TRACK JSONB, CONSTRAINT tracks_pkey PRIMARY KEY (ID));

DROP TABLE AREAS;
DROP TABLE ARTISTS;
DROP TABLE FORMATS;
DROP TABLE LABELS;
DROP TABLE LANGUAGES;
DROP TABLE MEDIUMS;
DROP TABLE PLACES;
DROP TABLE RECORDS;
DROP TABLE RELEASES;
DROP TABLE TRACKS;


UPDATE artists
SET artist = artist || '{"areaID": 1}'
WHERE artist @> '{"id":11000}';